### ISSUE TITLE
PDF output of html file

### ISSUE THREAD

**Issue by hetsch** [niwinz/phantompy#7]
Thanks for that nice project,

i'm having hard times finding a method for saving a html page to pdf.
Does something like this exist yet or do we have to implement that somehow?

**Comment by thethomaseffect** [comment]
That seems outside the scope of this project, you'd be better off piping the html out through something like https://github.com/chrisglass/xhtml2pdf

**Comment by niwinz** [comment]
Yeah, At first, as @thethomaseffect said, is out of scope of this project. But in the future they might consider implementing something similar.

Thanks @thethomaseffect  for quick reply
